### ISSUE TITLE
Cannot Start Test

### ISSUE THREAD

**Issue by cedrikl** [OSRTT/OSLTT#24]
**Describe the bug**
The test cannot start because SharpDX cannot be loaded.

**To Reproduce**

1. Connect OSLTT Probe
2. Open OSLTT
3. Click on Monitor Preset
4. Click Start Test
5. Button shows END TEST but nothing happens.

I read the getting started and didn't see if an additional install is required (msvcc runtimes for example) but I might be missing something.

**Expected behavior**
For the test window to show up.

**Screenshots**
<img width="823" alt="image" src="https://github.com/OSRTT/OSLTT/assets/24951043/6b50fc58-bb0a-4655-9ece-458a31e91628">

**Desktop (please complete the following information):**
 - OS: W11
 - Version: 22H2
 - Lenovo T14 G2 w/i5-1135G7

**Additional context**
Debug Log:

```
I1111101

Could not load file or assembly 'SharpDX, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)   at OSLTT.DirectX.System.DSystem.StartRenderForm(String title, Int32 width, Int32 height, Boolean vSync, Boolean fullScreen, Int32 display, Double fpsLimit)
   at OSLTT.Main.runDirectXTest()
I
```

**Comment by andymanic** [comment]
Thank you for the full bug report! That error normally means you are missing some files - can you manually download the ["Update Files"](https://github.com/OSRTT/OSLTT/releases) on the releases page and extract the contents to C:\OSLTT and try again?

**Comment by cedrikl** [comment]
I moved files 1 by 1 and it turned out to be the first one lol. It looks like a "OSLTT.exe.config" is required. I copied all files too but that one is the one that fixed the issue. Thank you so much, glad it was a simple one and didn't require much time on your side.

**Comment by cedrikl** [comment]
I moved files 1 by 1 and it turned out to be the first one lol. It looks like a "OSLTT.exe.config" is required. I copied all files too but that one is the one that fixed the issue. Thank you so much, glad it was a simple one and didn't require much time on your side.
