### ISSUE TITLE
Option to send mouse movement

### ISSUE THREAD

**Issue by RaedN0** [OSRTT/OSLTT#26]
Firing Animations and bullet decals are often delayed in games (see CS2 or Apex) and therefore are not really representable for the actual input lag

Instead of sending a mouse click you could send some mouse movement. If you now go in front of a dark space/wall and set the sensitivity high enough to instantly turn around you could use this for a more accurate measurement. After sending the movement just send the same amount but in the opposite direction to get back to the starting location.

Aperture Grille also did this in his input lag tests:
[Input Lag Revisited: V-Sync Off and NVIDIA Reflex](https://youtu.be/dPMHEyz38TM?si=Gy8a56NVjMMs8cnR&t=351)

**Comment by andymanic** [comment]
Closed as included as part of update V0.9
