### ISSUE TITLE
Weak audio output

### ISSUE THREAD

**Issue by bislog** [OSRTT/OSLTT#30]
**Describe the bug**
When testing audio latency, I noticed the new *beep* sound is weaker compared to the last software update (1.2 vs 1.4). This renders the OSLTT (non CS) unable to capture results even with the DUT's volume is already cranked to the max.

**To Reproduce**
OSLTT non-CS with 1.4 update

**Desktop (please complete the following information):**
 - OS: Windows 11 Latest

**Comment by andymanic** [comment]
As far as I'm aware, the audio testing hasn't changed for several versions now, so I can't say I know why the sound may be quieter in the most recent version. Can you double check the volume settings, including the volume mixer, to make sure that hasn't changed accidentally?

**Comment by bislog** [comment]
Hi! I've already double checked the settings and even tried it on the last DUT I've measured with the same outcome. Got this somewhat fixed though with a microphone amplifier. 

By the way, is the OSLTT's audio clip/beep from Windows? Perhaps one of the default sound wavs? If so I would like to know what the file name is just to double check.

**Comment by andymanic** [comment]
It's a sound I made myself - it's in the GitHub repo [here](https://github.com/OSRTT/OSLTT/blob/main/OSLTT/OSLTTTone.wav), although the program itself has it baked in to the resources so it isn't separately bundled. As far as I'm aware it shouldn't have changed at all. It's worth noting I do want to improve the audio latency testing as it isn't as low latency as it could (or should) be, so I will revisit it soon anyway.

**Comment by bislog** [comment]
Thanks for the info. This shall be closed for now.
