### ISSUE TITLE
Nothing work except screen flashing

### ISSUE THREAD

**Issue by iunewind** [OSRTT/OSLTT#31]
**Describe the bug**
Im bough osltt with osrtt half years ago, and used osrtt long time - its works well.
OSLTT used just now (need measure lag of projector, osrtt not working correct because lag too big). 
Im try to follow first "monitor" instruction from readme, but its seems not working for my. 

I installed the driver, ran the program, put the device with the sensor against the screen, pressed the “monitor” button and the start button. 
The screen went black with the fps counter in the corner. 
Then I pressed the button on the device and nothing happens. I can click the mouse - then the screen flashes, but nothing else happens. 
After exiting by ESC no result appears. 
I have tried changing modes - nothing works except black screen and white flashes. 
When closing the program it always gives an error  Safe handle has been closed no matter im tried start any test or no. 

Maybe im forgot some steps?

**Desktop (please complete the following information):**
Windows 11, last updates, 14700k, giga z790 gaming x, 64gb ddr5, rtx 4090 (all drivers updated)

**Comment by andymanic** [comment]
Hi there - when you press the button, can you try holding it for a second to see if that starts the test?

**Comment by andymanic** [comment]
Gotcha. When the DirectX window opens (when the screen goes black), can you/have you tried waiting ~30 seconds for the FPS counter to stabilise around 1000 FPS?

**Comment by iunewind** [comment]
> Gotcha. When the DirectX window opens (when the screen goes black), can you/have you tried waiting ~30 seconds for the FPS counter to stabilise around 1000 FPS?

Just tried to wait. No difference. And FPS stablize on 1000 in first seconds - its about 2-3sec and its show FPS 1000 with 1fps loating. CPU ussage about 1%.

**Comment by andymanic** [comment]
Ok, thank you for checking anyway. Can you tell me what firmware version your board is reporting in the top bar? Also, can you check if any of the other modes work, like the mouse testing mode? That would mean plugging in the mic, putting it next to your mouse, starting the mouse test, clicking a few times, then pressing the button on the tool to end the test. If that doesn't work then it's likely a firmware issue with the unit that we should be able to fix pretty easily.

**Comment by iunewind** [comment]
Its orange FW: N/A  in top right of bar, probably "n/a" its not good? :)
and yep, mouse test not working - when i start "Device connection" changed to "Test running" but nothing happen.

**Comment by iunewind** [comment]
also, when im plug deivce, its detected like usb flash "Arduiono" with files 
CURRENT.UF2
index.html
INFO_UF2.txt

**Comment by andymanic** [comment]
Yep that's not right! To reflash the firmware, close the main software and open OSLTTFlashTool.exe found in C:\OSLTT, and hit Flash OSLTT. You should hear the board disconnect and reconnect, then you can open the main software again and it should tell you the firmware version and work as normal. Let me know if it doesn't!

**Comment by iunewind** [comment]
Found OSLTTFlashTool.exe, its just 12kb size. When im start it nothing happen, sound of usb connect also not happend.
Im tryed also to start as admin and change usb port. No difference.

**Comment by iunewind** [comment]
also tried to start from command prompt - nothing, no any status strings 
![osltt-reflsh-cmd](https://github.com/user-attachments/assets/2507dbd2-fb03-46ae-a452-d49eb3400175)

**Comment by andymanic** [comment]
Ok, something isn't right so it'll be better to do it manually so that you can at least see any error messages. In command prompt can you run:
C:\OSLTT\arduinoCLI\arduino-cli.exe board list
then:
C:\OSLTT\arduinoCLI\arduino-cli.exe upload --port COM3 --fqbn Seeeduino:samd:seeed_XIAO_m0 -i C:\OSLTT\arduinoCLI\OSLTT_1.4.ino.bin
where you replace COM3 with whatever COM port your board is using on your system.
This should flash the board, and if not it should at least show an error message that we can use.

**Comment by iunewind** [comment]
in second command its error 

c:\OSLTT>C:\OSLTT\arduinoCLI\arduino-cli.exe upload --port COM4 --fqbn Seeeduino:samd:seeed_XIAO_m0 -i
Error: flag needs an argument: 'i' in -i
Usage:
  arduino-cli upload [flags]

**Comment by andymanic** [comment]
Oh sorry my bad, the file name needs to be in quotes like "C:\OSLTT\arduinoCLI\OSLTT_1.4.ino.bin"

**Comment by iunewind** [comment]
nope, my bad - im not understant that two string its one command : )
its looked flashed 
c:\OSLTT>C:\OSLTT\arduinoCLI\arduino-cli.exe upload --port COM4 --fqbn Seeeduino:samd:seeed_XIAO_m0 -i C:\OSLTT\arduinoCLI\OSLTT_1.4.ino.bin
Atmel SMART device 0x10010005 found
Device       : ATSAMD21G18A
Chip ID      : 10010005
Version      : v1.1 [Arduino:XYZ] Nov 27 2019 16:35:59
Address      : 8192
Pages        : 3968
Page Size    : 64 bytes
Total Size   : 248KB
Planes       : 1
Lock Regions : 16
Locked       : none
Security     : false
Boot Flash   : true
BOD          : true
BOR          : true
Arduino      : FAST_CHIP_ERASE
Arduino      : FAST_MULTI_PAGE_WRITE
Arduino      : CAN_CHECKSUM_MEMORY_BUFFER
Erase flash
done in 0.823 seconds

Write 43200 bytes to flash (675 pages)
[==============================] 100% (675/675 pages)
done in 0.351 seconds

Verify 43200 bytes of flash with checksum.
Verify successful
done in 0.058 seconds
CPU reset.

**Comment by iunewind** [comment]
FW 1.4

**Comment by andymanic** [comment]
Excellent! That should be working as normal now

**Comment by iunewind** [comment]
FW 1.4, now, device flash green led :) its not happen before )
And yes, monitors test pass ok, with result after testing, looks its works fine now.Thanks a lot! )

**Comment by andymanic** [comment]
Perfect, glad we've got it working. Will close this issue as it's resolved - but if you have any other issues please do let me know!
